#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TimeTrackerUniversal.Resource", IsApplication=true)]

namespace TimeTrackerUniversal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ttu = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002d
			public const int ClockInAndOutLayOut = 2131099693;
			
			// aapt resource value: 0x7f060049
			public const int DateSelectorButtons = 2131099721;
			
			// aapt resource value: 0x7f060008
			public const int EnterTimeOutlbl = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int EnterTimeinlbl = 2131099654;
			
			// aapt resource value: 0x7f06002f
			public const int ForReal = 2131099695;
			
			// aapt resource value: 0x7f06004d
			public const int ImportPunchesLayout = 2131099725;
			
			// aapt resource value: 0x7f06000b
			public const int IsClockIn = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int IsClockOut = 2131099660;
			
			// aapt resource value: 0x7f060035
			public const int LabelsForHourDataLayout = 2131099701;
			
			// aapt resource value: 0x7f060033
			public const int OutputText = 2131099699;
			
			// aapt resource value: 0x7f06002c
			public const int Root = 2131099692;
			
			// aapt resource value: 0x7f060031
			public const int TimeClockOut = 2131099697;
			
			// aapt resource value: 0x7f060039
			public const int ValuesForHourDataLayout = 2131099705;
			
			// aapt resource value: 0x7f060040
			public const int btnAddPunch = 2131099712;
			
			// aapt resource value: 0x7f06003e
			public const int btnChangeEmails = 2131099710;
			
			// aapt resource value: 0x7f060050
			public const int btnClearDB = 2131099728;
			
			// aapt resource value: 0x7f06002e
			public const int btnClockIn = 2131099694;
			
			// aapt resource value: 0x7f060030
			public const int btnClockOut = 2131099696;
			
			// aapt resource value: 0x7f060051
			public const int btnDeleteLastPunch = 2131099729;
			
			// aapt resource value: 0x7f060043
			public const int btnEditPunch = 2131099715;
			
			// aapt resource value: 0x7f06002a
			public const int btnExecuteSql = 2131099690;
			
			// aapt resource value: 0x7f06003f
			public const int btnExit = 2131099711;
			
			// aapt resource value: 0x7f06000f
			public const int btnExitPass = 2131099663;
			
			// aapt resource value: 0x7f060025
			public const int btnExport = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int btnImport = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int btnOk = 2131099684;
			
			// aapt resource value: 0x7f060028
			public const int btnOkEmail = 2131099688;
			
			// aapt resource value: 0x7f06000d
			public const int btnPunch = 2131099661;
			
			// aapt resource value: 0x7f060042
			public const int btnSqlQuery = 2131099714;
			
			// aapt resource value: 0x7f060044
			public const int btnViewHistory = 2131099716;
			
			// aapt resource value: 0x7f060054
			public const int btnViewHistoryExit = 2131099732;
			
			// aapt resource value: 0x7f06004e
			public const int btnViewTimeframe = 2131099726;
			
			// aapt resource value: 0x7f06003d
			public const int buttons1 = 2131099709;
			
			// aapt resource value: 0x7f060041
			public const int buttons2 = 2131099713;
			
			// aapt resource value: 0x7f06004f
			public const int chkClearAll = 2131099727;
			
			// aapt resource value: 0x7f060004
			public const int dateDate = 2131099652;
			
			// aapt resource value: 0x7f06004a
			public const int datePickerFromDate = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int datePickerToDate = 2131099723;
			
			// aapt resource value: 0x7f060003
			public const int enterDatelbl = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int lblEmail = 2131099669;
			
			// aapt resource value: 0x7f060046
			public const int lblEnterQuery = 2131099718;
			
			// aapt resource value: 0x7f060038
			public const int lblGrossPayMonth = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int lblMonthTotalHours = 2131099703;
			
			// aapt resource value: 0x7f060021
			public const int lblOut = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int lblOutEmail = 2131099682;
			
			// aapt resource value: 0x7f060012
			public const int lblPass = 2131099666;
			
			// aapt resource value: 0x7f060036
			public const int lblWeekTotalHours = 2131099702;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout10 = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout11 = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1V = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout2V = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout3 = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout3H = 2131099665;
			
			// aapt resource value: 0x7f060020
			public const int linearLayoutEmail1V = 2131099680;
			
			// aapt resource value: 0x7f060014
			public const int linearLayoutEmailH = 2131099668;
			
			// aapt resource value: 0x7f060023
			public const int linearLayoutEmailV = 2131099683;
			
			// aapt resource value: 0x7f060013
			public const int pass1 = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int punchOut = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int scrollView2 = 2131099648;
			
			// aapt resource value: 0x7f060045
			public const int scrollView3 = 2131099717;
			
			// aapt resource value: 0x7f06002b
			public const int scrollViewMain = 2131099691;
			
			// aapt resource value: 0x7f060029
			public const int sqlQuery = 2131099689;
			
			// aapt resource value: 0x7f060017
			public const int textView1 = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int textView10 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int textView11 = 2131099678;
			
			// aapt resource value: 0x7f060007
			public const int timePickIn = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int timePickOut = 2131099657;
			
			// aapt resource value: 0x7f060019
			public const int txtBCCNewEmail = 2131099673;
			
			// aapt resource value: 0x7f060052
			public const int txtFileName = 2131099730;
			
			// aapt resource value: 0x7f060018
			public const int txtFromNewEmail = 2131099672;
			
			// aapt resource value: 0x7f06003c
			public const int txtGrossPay = 2131099708;
			
			// aapt resource value: 0x7f060053
			public const int txtImportOutput = 2131099731;
			
			// aapt resource value: 0x7f06004c
			public const int txtIntervalTotalHours = 2131099724;
			
			// aapt resource value: 0x7f060032
			public const int txtLastPunch = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int txtMainOut = 2131099700;
			
			// aapt resource value: 0x7f06003b
			public const int txtMonthTotalHours = 2131099707;
			
			// aapt resource value: 0x7f060027
			public const int txtNewEmail = 2131099687;
			
			// aapt resource value: 0x7f060048
			public const int txtOutput = 2131099720;
			
			// aapt resource value: 0x7f06001c
			public const int txtRate = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int txtServer = 2131099679;
			
			// aapt resource value: 0x7f060047
			public const int txtSqlQuery = 2131099719;
			
			// aapt resource value: 0x7f060016
			public const int txtToNewEmail = 2131099670;
			
			// aapt resource value: 0x7f06003a
			public const int txtWeekTotalHours = 2131099706;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddPunch = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ChangeEmails = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ChangeSettings = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RunSQL = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ViewHistory = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int alter_email_address = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int dbPath = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int from_email_address = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int initialPay = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int not_real_output = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int pass = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int real_output = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int server = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
